version: '3.1'

services:
  pprgo:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports:
      -  8080:8080
    volumes:
      - .:/home
    command: jupyter-lab --ip=0.0.0.0 --allow-root --no-browser --port 8080  --NotebookApp.token=''
